### ISSUE TITLE
Enabling network statistics crashes Tribler

### ISSUE THREAD

**Issue by qstokkink** [qstokkink/TriblerExperimental#105]
Clicking the enable statistics setting and then restarting causes the following crash:

```python
Traceback (most recent call last):
  File "src/run_tribler.py", line 105, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "src/run_tribler.py", line 86, in main
    session = Session(config)
  File "src/tribler/core/session.py", line 88, in __init__
    self.ipv8 = IPv8(self.config.get("ipv8"), enable_statistics=self.config.get("statistics"))
  File "pyipv8/ipv8_service.py", line 108, in __init__
    self.endpoint = DispatcherEndpoint(list(endpoint_args.keys()), **endpoint_args)
  File "pyipv8/ipv8/messaging/interfaces/dispatcher/endpoint.py", line 91, in __init__
    self.interfaces = {interface: INTERFACES[interface](**(kwargs.get(interface, {}))) for interface in interfaces}
  File "pyipv8/ipv8/messaging/interfaces/dispatcher/endpoint.py", line 91, in <dictcomp>
    self.interfaces = {interface: INTERFACES[interface](**(kwargs.get(interface, {}))) for interface in interfaces}
TypeError: UDPEndpoint.__init__() got an unexpected keyword argument 'worker_threads'
```

**Comment by qstokkink** [comment]
I think the following happens:

1. Tribler runs with Rust enhancements. The `worker_threads` setting is saved:

https://github.com/qstokkink/TriblerExperimental/blob/fec2f27770a35cfefe1ffd759a9fa961bc8a101c/src/tribler/core/session.py#L54

2. The statistics are enabled and Tribler is restarted. The `nullcontext` does not do anything because the statistics are incompatible with the Rust enhancements and Tribler crashes due to the leftover setting.

https://github.com/qstokkink/TriblerExperimental/blob/fec2f27770a35cfefe1ffd759a9fa961bc8a101c/src/tribler/core/session.py#L87-L88

---

If the Rust enhancements are not available at all, we do properly clean the config setting:

https://github.com/qstokkink/TriblerExperimental/blob/fec2f27770a35cfefe1ffd759a9fa961bc8a101c/src/tribler/core/session.py#L60-L64
