### ISSUE TITLE
transport_received() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by qstokkink** [qstokkink/TriblerExperimental#48]
After the type refactorings the following error gets logged:

```python
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python310\lib\asyncio\proactor_events.py", line 585, in _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:\TriblerExperimental\src\tribler\core\socks5\client.py", line 61, in datagram_received
    self.callback(request.data, request.destination)
TypeError: UdpSocketManager.transport_received() takes 2 positional arguments but 3 were given
```

**Comment by qstokkink** [comment]
https://github.com/qstokkink/TriblerExperimental/blob/f80223fd4006b8305b893a3536a00fd54cd9b8ed/src/tribler/core/torrent_checker/torrentchecker_session.py#L237

This should be `self.datagram_received` instead of `self.transport_received`.

**Comment by qstokkink** [comment]
PyCharm does seem to detect this violation correctly:

![screenshot](https://github.com/qstokkink/TriblerExperimental/assets/3630389/27cbfc55-74bb-4511-ac69-ef452ea2737f)

This must be a MyPy bug/shortcoming.
